# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jWwyW_i6-Hr0K-NtsorwigLmEcwShUln
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

from google.colab import files
files.upload()

import os
print(os.listdir())

from IPython.display import Image, display

display(Image("pexels-venkat-ragavan-363659-982021.jpg"))

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

results = model("pexels-venkat-ragavan-363659-982021.jpg")
results[0].show()

!pip install ultralytics

from ultralytics import YOLO
import os

from google.colab import files
files.upload()

print(os.listdir())

model = YOLO("yolov8n.pt")

results = model("20260308-0844-56.8703174.mp4", save=True)

results = model("20260308-0844-56.8703174.mp4", save=True)

results = model("20260308-0844-56.8703174.mp4", save=True, project="runs", name="new_run")

import os
from IPython.display import Video

files = os.listdir("/content/runs/detect/runs/new_run")
print(files)

Video("/content/runs/detect/runs/new_run/" + files[0], embed=True)

from google.colab import files

files.download('/content/runs/detect/runs/new_run/20260308-0844-56.8703174.avi')

from google.colab import files
uploaded = files.upload()

from IPython.display import Video

Video("20260308-0844-56.8703174.avi", embed=True)

!ffmpeg -i 20260308-0844-56.8703174.avi output.mp4

from IPython.display import Video
Video("output.mp4", embed=True)

from IPython.display import HTML

HTML("""
<video width="600" controls>
  <source src="output.mp4" type="video/mp4">
</video>
""")